version: '3.5'
# Contains everything needed to run scheduling
services:
  wkhtml-node:
    container_name: wkhtml-node
    image: "wkhtml-node-container"
    build:
      context: .
    ports:
      - "${CONTAINER_PORT}:${TARGET_PORT}"
    environment:
      - GATEWAY_URL=${GATEWAY_URL}
      - JWT_KEY=${JWT_KEY}
      - PORT=${CONTAINER_PORT}
